# Generated by Django 3.2.25 on 2024-04-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240415_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ManyToManyField(related_name='sales', to='main.Client'),
        ),
    ]
